name: Create pull requests from master
on:
  #Push trigger
  push:
    branches:
      - master
  #Manual dispatch trigger
  workflow_dispatch:
  #Remote github trigger
  repository_dispatch:
    types: execute

jobs:
  build:
    # Job name is Greeting
    name: Create Pull Requests
    # This runs the job on ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Creates pull requests
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          gh pr create --title "Merge from master" --body "Auto merge PR" --head doitandbedone:master --base vlc-support
          gh pr create --title "Merge from master" --body "Auto merge PR" --head doitandbedone:master --base feature/workflow-version-tagger
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
